/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;
// Importa las clases de la lógica
import com.mycompany.logica.ListaAdyacencia;
import com.mycompany.logica.Tren;
import com.mycompany.logica.Micro;
import com.mycompany.logica.Nodo;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import igu.Pantalla2;
import igu.Pantalla3;
import igu.Elimin;
import java.util.Scanner;

/**
 *
 * @author JOVANNI SG
 */
public class Pantalla extends javax.swing.JFrame {
//ListaAdyacencia listaTransporte = new ListaAdyacencia();
ListaAdyacencia listaTransporte; // Lista original
ListaAdyacencia listaDeserializada; // Lista deserializada
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        listaTransporte = new ListaAdyacencia(); // Inicializar aquí
        //listaDeserializada = new ListaAdyacencia(); // Inicializar aquí
        initComponents();
        
        // Inicializa algunos datos de ejemplo en el constructor de la ventana
        
        deserializarListaTransporte(); // Llama a deserializar
    }
    // Este método inicializa los datos de transporte que tienes en la lógica
    private void inicializarDatos() {
        
        Tren tren3a1 = new Tren("CUCEI", 3, "Calz Revolucion", 6, 10, false, 132, 'A');
        Tren tren3a2 = new Tren("Revolucion", 3, "Ramon lopez Velarde", 2, 3, false, 132, 'A');
        Tren tren2a1 = new Tren("Juarez", 2, "Av.Juarez", 6, 10, true, 132, 'A');
        
        Micro micro1 = new Micro("Monumental", 1, "Fidel Velasquez", 6, 10, true, 132, 'A');
        Micro micro2 = new Micro("Monte Olimpo", 1, "Monte Olivete", 6, 10, false, 132, 'A');
        Micro micro3 = new Micro("Igualdad", 1, "San Simon", 6, 10, false, 132, 'A');

        // Agregar nodos (estaciones)
        listaTransporte.agregarNodo(tren3a1.getNombre(), tren3a1);
        listaTransporte.agregarNodo(tren3a2.getNombre(), tren3a2);
        listaTransporte.agregarNodo(tren2a1.getNombre(), tren2a1);
        listaTransporte.agregarNodo(micro1.getNombre(), micro1);
        listaTransporte.agregarNodo(micro2.getNombre(), micro2);
        listaTransporte.agregarNodo(micro3.getNombre(), micro3);

        // Establecer adyacencias (conexiones entre estaciones)
        listaTransporte.agregarAdyacencia(tren3a1.getNombre(), tren3a2.getNombre());
        listaTransporte.agregarAdyacencia(micro1.getNombre(), micro2.getNombre());
        listaTransporte.agregarAdyacencia(micro2.getNombre(), micro1.getNombre());
        listaTransporte.agregarAdyacencia(micro2.getNombre(), micro3.getNombre());
        listaTransporte.agregarAdyacencia(micro3.getNombre(), micro2.getNombre());
    
    
    // SERIALIZAR listaTransporte
    try (FileOutputStream fileOut = new FileOutputStream("listaTransporte.ser");
         ObjectOutputStream out = new ObjectOutputStream(fileOut)) {
        out.writeObject(listaTransporte);
        System.out.println("Lista de transporte serializada y guardada en listaTransporte.ser");
    } catch (IOException e) {
        e.printStackTrace();
    }
    }
  private void deserializarListaTransporte() {
    // DESERIALIZAR listaTransporte
    try (FileInputStream fileIn = new FileInputStream("listaTransporte.ser");
         ObjectInputStream in = new ObjectInputStream(fileIn)) {
        listaDeserializada = (ListaAdyacencia) in.readObject(); // Cambiado para asignar a la variable de instancia
        System.out.println("Lista de transporte deserializada con éxito.");
    } catch (IOException | ClassNotFoundException e) {
        e.printStackTrace();
        listaDeserializada = null; // Asegúrate de que sea nulo si hay un error
    }

    // Verificación para asegurarse de que la lista fue deserializada correctamente
    if (listaDeserializada == null) {
        inicializarDatos();
        System.out.println("Error: No se pudo deserializar la lista de transporte.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        odcion1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        odcion2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFibal = new javax.swing.JTextPane();
        AGREAR = new javax.swing.JButton();
        ConEst = new javax.swing.JToggleButton();
        Elim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("STPMG");

        odcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odcion1ActionPerformed(evt);
            }
        });

        jLabel2.setText("¿Qué vehículo quieres saber? 1-Micro 2-Tren:");

        jLabel3.setText("¿Qué línea  quieres?");

        odcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odcion2ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar");
        jButton2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jButton2ComponentMoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtFibal);

        AGREAR.setText("NUEVO");
        AGREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREARActionPerformed(evt);
            }
        });

        ConEst.setText("Conecar estaciones");
        ConEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConEstActionPerformed(evt);
            }
        });

        Elim.setText("ELIMINAR");
        Elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(odcion2)
                            .addComponent(odcion1))
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConEst)
                .addGap(72, 72, 72)
                .addComponent(Elim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AGREAR))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGREAR)
                    .addComponent(ConEst)
                    .addComponent(Elim))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void odcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odcion1ActionPerformed

        
    }//GEN-LAST:event_odcion1ActionPerformed

    private void odcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odcion2ActionPerformed

    private void jButton2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ComponentMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // Obtener las opciones seleccionadas por el usuario
            int vehiculoSeleccionado = Integer.parseInt(odcion1.getText()); // 1 para Micro, 2 para Tren
            int lineaSeleccionada = Integer.parseInt(odcion2.getText());

            // Variable para almacenar el resultado
            String resultado = "";

            // Según el tipo de vehículo
            if (vehiculoSeleccionado == 1) {
                // Mostrar los micros de la línea seleccionada
                resultado = listaDeserializada.mostrarElementosPorClaseYLinea("Micro", lineaSeleccionada);
                
            } else if (vehiculoSeleccionado == 2) {
                // Mostrar los trenes de la línea seleccionada
                resultado = listaDeserializada.mostrarElementosPorClaseYLinea("Tren", lineaSeleccionada);
            } else {
                // Si la opción no es válida
                JOptionPane.showMessageDialog(this, "Opción no válida. Selecciona 1 para Micro o 2 para Tren.");
                return;
            }

            // Mostrar el resultado en el JTextPane
            txtFibal.setText(resultado);

        } catch (NumberFormatException e) {
            // Manejar el error si el usuario no ingresa números válidos
            JOptionPane.showMessageDialog(this, "Por favor ingresa números válidos en las opciones.");
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AGREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREARActionPerformed
        // TODO add your handling code here:
        Scanner scanner = new Scanner(System.in);
        Pantalla2 panta = new Pantalla2(this);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_AGREARActionPerformed

    private void ConEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConEstActionPerformed
        // TODO add your handling code here:
          Scanner scanner = new Scanner(System.in);
        Pantalla3 panta = new Pantalla3(this);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_ConEstActionPerformed

    private void ElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimActionPerformed
        // TODO add your handling code here:
         Scanner scanner = new Scanner(System.in);
        Elimin panta = new Elimin(this);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_ElimActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREAR;
    private javax.swing.JToggleButton ConEst;
    private javax.swing.JButton Elim;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField odcion1;
    private javax.swing.JTextField odcion2;
    private javax.swing.JTextPane txtFibal;
    // End of variables declaration//GEN-END:variables
}
